//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public int ListaID { get; set; }
        public int ProdutoID { get; set; }
        public Nullable<decimal> QtdPrevista { get; set; }
        public Nullable<decimal> QtdReal { get; set; }
        public string Marca { get; set; }
        public Nullable<decimal> Preco { get; set; }
    
        public virtual Lista Lista { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
