//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoPicklist
    {
        public int ID { get; set; }
        public string Categoria { get; set; }
        public string Produto { get; set; }
        public bool ListaPadrao { get; set; }
        public string Unidade { get; set; }
        public Nullable<decimal> QtdNormal { get; set; }
    }
}
